5 patch api reviews reviewid
Evil-Pablo/NC---Games pull request #4
Opened 2022-07-06 10:38 UTC by Evil-Pablo

PATCH review by ID test completed and updated model & controller.
Error handling updated for GET & PATCH review by ID.

2022-07-06 10:59 UTC, douglashellowell commented on __tests__/app.test.js
> +        const REVIEW_ID = 1;
great use of `const` variables in tests

you should use this to match the `review_id` in the returned review too!

```diff
{
- review_id: 1,
+ review_id: REVIEW_ID,
}
```

🌟

2022-07-06 11:06 UTC, douglashellowell requested changes
great stuff!

Lots of changes in this PR related to `GET /api/reviews/:review_id` - try your best to keep these in their own PRs!


There are some more tests needed for `PATCH /api/reviews/:review_id`

think about 

```
/api/review/999999
/api/review/not-an-id

and

/api/review/1  { wrong-key: 1 }
```

2022-07-06 14:50 UTC, Dutton1990 commented
You could add one more test for api/review/999, this should return a 404 not found as it's a valid id but doesn't exist :)

2022-07-07 10:43 UTC, Angaca approved these changes
Ready for merge!

2022-07-07 11:06 UTC, merged